export const STRINGS = {
  appName: '知行',
  wordmark: '知行',
  back: '返回',
  settings: '设置',
  exportJson: '导出 JSON',
  importJson: '导入 JSON',
  exportReminder: 'iOS 可能清理本地数据，建议偶尔导出备份。',
  importConfirm: '导入将替换当前全部内容，确定吗？',
  confirmImport: '确认导入',
  cancel: '取消',
  importFailed: '导入失败',
  about: '关于',
  aboutBody: '本地优先，无账号，无后端。',
  appearance: '外观',
  themeSystem: '跟随系统',
  themeLight: '浅色',
  themeDark: '深色',
  resetData: '恢复初始数据',
  confirmResetData: '确认恢复',
  resetDataPrompt: '这会删除当前所有卡片并恢复初始示例。',
  cardGrid: '卡片',
  addCard: '添加',
  addDomain: '添加领域',
  addInputLabel: '新卡片标题',
  edit: '编辑',
  reorder: '排序',
  editCard: '编辑卡片',
  title: '标题',
  subtitle: '副标题（可选）',
  color: '颜色',
  mark: '标记',
  moveTo: '移动到',
  rootLevel: '根级',
  done: '完成',
  close: '关闭',
  delete: '删除',
  confirmDelete: '确认删除',
  undo: '撤销',
  deletedUndo: '已删除 · 撤销',
  emptyTitle: '还没有卡片',
  emptyBody: '点下面的「添加」，放进第一张。',
} as const
